### PR TITLE
Login page change

### PR DESCRIPTION
**Pull request by santoshdvc**
Changes to login page:

- Centered the elements
- Changed style of button and text-box
- Changed the size of elements
- Added fade-in animation to the page

I also, have added few fade-in CSS animations with different timings, so you can use them later.
``` html
<div class="fadeIn first"></div>
<div class="fadeIn second"></div>
```
## Screenshot of Login Page
login_page_changes

### CODE REVIEW

**Review by Swanand01 — COMMENTED** [review]
Hi!
This new design looks fantastic!
The only change I will suggest is to keep the name of the input field as it was before, i.e password since it is referenced in app.py.

```
@app.route('/', methods=['GET', 'POST'])
def login():
    password = request.form.get("password")
    print(password, type(password))
    if password == configs["password"]:
        session["logged_in"] = True
        return redirect(url_for('autoindex'))
    else:
        session["logged_in"] = False
        return render_template('__autoindex__/login.html')
```

Also, please do add a required tag in the password input field. Thanks.

**Comment by santoshdvc** [comment]
Okay. I will add and submit the changes back.

**Comment by santoshdvc** [comment]
Hi, 
I have commited the change as described above. Please verify them.

**Comment by Swanand01** [comment]
The name for the password input still seems to be login. It will need to be changed to password.

**Comment by santoshdvc** [comment]
I have commited the change. Please verify them.

**Comment by Swanand01** [comment]
Thanks for your time and effort. The login page now looks great.
If you would like to, you are free to contribute to the design of the main page as well.
Thanks!

**Pull request merged**
